added blocking commands tests
amazon-contributing/redis-rs pull request #169
Opened 2024-07-03 17:06 UTC by avifenesh

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-04 07:50 UTC, ikolomi commented on redis/tests/test_blocking_commands.rs
I dont think a single tests justifies having it in a new file, its better to keep them together in the test_cluster_async.rs

2024-07-04 07:53 UTC, avifenesh commented on redis/tests/test_blocking_commands.rs
To my understanding we are planing to create state restoration at some point, so i thought it is better to create a new file ready to add massive tests when we will have the support. can move back if you think its better.

2024-07-04 08:27 UTC, ikolomi requested changes

2024-07-04 08:27 UTC, ikolomi commented on redis/tests/test_blocking_commands.rs
> +    async fn test_blocking_command_when_cluster_drops() {
why to invent a different logic and form - copy paste and modify:  https://github.com/amazon-contributing/redis-rs/blob/4571c91e2165b9ebf3bb9a3dff0991bc453d1075/redis/tests/test_cluster_async.rs#L3680

2024-07-04 08:27 UTC, ikolomi commented on redis/tests/test_blocking_commands.rs
> +    async fn test_blocking_command_when_cluster_drops() {
you can add your test below that one

2024-07-14 06:17 UTC, ikolomi approved these changes

2024-07-14 07:28 UTC, merged