Fix for serverless
amazon-contributing/redis-rs pull request #175
Opened 2024-07-22 16:02 UTC by barshaul

- Improve logging
- Removed IP checks from the connection logic: On different managed services the given endpoints are actually load balancers and the same DNS entry of a "node" might be routed to different IPs of different LBs. That means that we shouldn't fail the creation of management connection on "mismatched IPs" found between the user and the management connection.

2024-07-23 07:41 UTC, eifrah-aws commented on redis/src/aio/connection.rs
> +fn log_conn_creation<T>(conn_type: &str, node: T, ip: Option<IpAddr>)
nit: please document this method...

2024-07-24 15:44 UTC, eifrah-aws requested changes

2024-07-25 15:20 UTC, eifrah-aws approved these changes

2024-07-26 07:56 UTC, barshaul commented on redis/src/cluster_async/connections_logic.rs
> +            let conn = node.user_connection.conn.clone();
Senders (e.g. the connection in this example) are being cloned cheaply (Sender::clone is essentially a reference count increment, comparable to Arc::clone)

2024-07-26 09:55 UTC, merged